### ISSUE TITLE
PHP 8+ compatible

### ISSUE THREAD

**Issue by RosiersRobin** [gocanto/http-client#8]
Please make the package PHP 8.0, 8.1 and 8.2 compatible.

**Comment by gocanto** [comment]
Hi @RosiersRobin - thank you for your interest in this package. 

I have been really busy lately and I forgot to do it. Would you be up for the challenge? 

Looking forward to hearing back from you.

**Comment by RosiersRobin** [comment]
Hi @gocanto I made a PR for you https://github.com/gocanto/http-client/pull/9

**Comment by gocanto** [comment]
Closed by https://github.com/gocanto/http-client/pull/10

Thanks.
